### ISSUE TITLE
This doesn't work with Python3

### ISSUE THREAD

**Issue by jacksonofalltrades** [HDE/python-lambda-local#13]
$ python-lambda-local
Traceback (most recent call last):
  File "/Users/dej/wa/dragonfly/bigsur/venv/bin/python-lambda-local", line 11, in <module>
    load_entry_point('python-lambda-local==0.1.3', 'console_scripts', 'python-lambda-local')()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/dej/wa/dragonfly/bigsur/venv/lib/python3.6/site-packages/lambda_local/__init__.py", line 10, in <module>
    from main import run
ModuleNotFoundError: No module named 'main'

Any suggestions? Thanks.

**Comment by jacksonofalltrades** [comment]
It seems that this works properly if you prefix "main", "event", and "timeout" with "lambda_local.". Python3 doesn't seem to like the relative imports for these modules.

**Comment by yxd-hde** [comment]
I saw a version 0.1.3 in your path. Have you tried version 0.1.4?

**Comment by jacksonofalltrades** [comment]
Oh I thought I had installed 0.1.4. I'll check again, thanks.

**Comment by jacksonofalltrades** [comment]
Yes, that worked. Apologies.
