### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by seans11** [HDE/python-lambda-local#26]
Error I'm receiving when running in Windows 10 with Python 3.6.2-32:
```powershell
PS C:\Projects\test> python-lambda-local -t 15 -f lambda_handler .\test.py event.json
[root - INFO - 2017-12-11 10:13:42,817] Event: {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
[root - INFO - 2017-12-11 10:13:42,817] START RequestId: 2df1ccc9-ba8a-48b8-aad4-ac41541a1e96
Process Process-1:
Traceback (most recent call last):
  File "c:\program files (x86)\python\python36-32\lib\site-packages\lambda_local\main.py", line 87, in execute
    with time_limit(context.timeout):
  File "c:\program files (x86)\python\python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\program files (x86)\python\python36-32\lib\site-packages\lambda_local\timeout.py", line 18, in time_limit
    signal.signal(signal.SIGALRM, signal_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

I found the following issue raised from another project which might explain the problem:
https://github.com/Unity-Technologies/ml-agents/issues/7

Looks like this is a Windows specific issue when calling signal.SIGALRM.

**Comment by yxd-hde** [comment]
PR is welcomed to fix this on windows. Thanks.

**Comment by scarolan** [comment]
I'm glad someone reported this and that it's a known issue.  I'm also seeing the same thing.  I'll try and track down the cause.

**Comment by yxd-hde** [comment]
See: #32

**Comment by naveenbharadwaj19** [comment]
Trying to get a playlist details by youtube api but getting error 
`signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'
`
python version : 3.7.7 64bit os: Windows 10 

how to solve this ? 
@yxd-hde  i read the docs you mentioned but i couldn't understand it
